### ISSUE TITLE
great guide -- any thoughts of working with Debian team to incorporate it into the installer?

### ISSUE THREAD

**Issue by imthenachoman** [david-cortes/snapper-in-debian-guide#1]
openSUSE Tumbleweed installer does all this automatically when you install using btrfs and with snapshot support.

Your guide seems to be how to replicate that with Debian. 

I'm about to wipe openSUSE Tumbleweed and replace it with Debian 12 and will try your guide. 

I was just wondering if you've thought about working with Debian team to have it added to the installer...

**Comment by david-cortes** [comment]
That's definitely outside of my area of expertise. There's some discussions about it in [grub-btrfsd](https://github.com/Antynea/grub-btrfs) if you want to read more about the challenges of doing so and progress in that regard.

**Comment by imthenachoman** [comment]
I'm going to see if I can ask the Debian installer folks about adding this to the installer. I feel like it's real value add.

**Comment by imthenachoman** [comment]
Thanks again!
