### ISSUE TITLE
How to boot rolled back snapshot in read/write mode?

### ISSUE THREAD

**Issue by imthenachoman** [david-cortes/snapper-in-debian-guide#2]
I followed your guide but when I tried to rollback, it still boots into read only mode.

I am not sure if there is a step I missed or if there is something wrong with `snapper-rollback`. I opened an issue there too: https://github.com/jrabinow/snapper-rollback/issues/15.

**Comment by imthenachoman** [comment]
I wiped my system and reinstalled again. I followed your guide agian.

I was able to boot into the `pre` snapshot -- the one created before I installted `atop`.

I did a `sudo snapper-rollback 3` and it said to reboot.

But when I reboot and load the default GRUB entry, it is sitll in read/only mode. 

I'm not able to figure out what is wrong. Any ideas?

**Comment by david-cortes** [comment]
Actually, I just noticed that I also have that `ro` flag on `/proc/cmdline`, but the root subvolume is actually writable. Does it error out if you try to `sudo touch` something under `/`?

**Comment by imthenachoman** [comment]
I think I fixed it. I did a fresh install and changed/fixed a few things. I'm not sure which one fixed the issue but I was able to do a rollback and boot into it.

The two things I changed:

- I was following your guide literally and I didn't pay attention.
  - In your guide, you delete the `/` partition the guided setup creates, and then you create a `/boot` one.
  - In my installation, the guided setup created a `/boot` so I ended up with two:
    1. one that got mounted as `/boot/efi`
    2. the one I created that mounted as `/boot`.
  - So, basically, the only thing I had to do was do the guided setup for partition and then change the `/` partition from `ext4` to `btrfs`.
- In my `/etc/fstab`, I used the `UUID` instead of device name.
  - You got the device name using:
    ```
    df --output=source / | tail -n 1
    ```
  - I used this to get the UUID:
    ```
    sudo blkid -i -p -o export $(df --output=source / | tail -n 1) | grep '^UUID='
    ```
  - For adding to `/etc/fstab`:
    ```
    printf "$(sudo blkid -i -p -o export $(df --output=source / | tail -n 1) | grep '^UUID=') /btrfsroot    btrfs    defaults,subvolid=5    0    0\n" | sudo tee -a /etc/fstab
    ```
