### ISSUE TITLE
Suggestion: Mention Timeshift as alternative to snapper and why it might work better for some

### ISSUE THREAD

**Issue by danboid** [david-cortes/snapper-in-debian-guide#5]
Hi David

Thanks for writing this very handy guide! It is a great companion to SpiralLinux for how to configure Debian for BTRFS snapshot use. I found it especially useful for your description of how to restore @home subvolumes under Debian.

I have noticed that it currently makes no mention of using Timeshift as an alternative to snapper, and I think it probably should.

There are two main advantages of using Timeshift instead of snapper. Restoring timeshift snapshots when you also want to restore your home dir is much easier using the timeshift gui than using snapper-rollback or the snapper command. snapper-rollback currently only supports rolling back the root subvolume and I have had no luck using btrfs-assistant to rollback although it works fine for creating and deleting snapper snapshots. When you restore a timeshift snapshot using timeshift-gui, it asks if you also want to rollback your @home subvolume snapshot too.

timeshift-gui also lets you easily browse and copy individual files and folders from within snapshots, a feature missing from both snapper-gui and btrfs-assistant.

Note that when you install Debian from its live installers (which uses the Calamares based GUI installer) if you install using BTRFS the Debian live installer will automatically configure your BTRFS subvolumes in the way required to use timeshift. Unfortunately the standard Debian installer does not configure any BTRFS subvolumes, as you know.

Hence, if you want to install Debian for use with snapper you should install SpiralLinux and f you want to use timeshift then you should install using the Debian Live graphical installer.

I have successfully used timeshift under Debian with grub-btrfs in a very similar manner to what you describe in your guide. For people who only want to create manual snapshots, timeshift might be a better choice.

Do you think this might justify adding a small section to you guide to cover these points, so people know there is an alternative?

EDIT

I forgot to mention, the big disadvantage of timeshift versus snapper is that timeshift only supports one subvolume configuration (@ for root and @home for /home) whereas snapper gives the user much more freedom in configuration. 

It is best to minimise the number of subvolumes and snapshots per subvolume. Both should be kept to having no more than about 10.

Hopefully snapper-rollback will get updated to support rolling back @home and other subvolumes.

**Comment by imthenachoman** [comment]
I would be curious how many of the steps would have to be altered for Timeshift?

And I think this guide is using Snapper since that is what openSUSE uses. openSUSE's installation process includes snapper out of the box.

**Comment by danboid** [comment]
This guide says in the introductory paragraph

`The tutorial is inspired by the [SpiralLinux](https://github.com/SpiralLinux/SpiralLinux-project) distribution, which configures this automatically upon install.`

It uses snapper because SpiralLinux uses snapper by default.

**Comment by imthenachoman** [comment]
Ah, my bad!

**Comment by danboid** [comment]
I forgot to mention, the big disadvantage of timeshift versus snapper is that timeshift only supports one subvolume configuration (@ for root and @home for /home) whereas snapper gives the user much more freedom in configuration.

**Comment by david-cortes** [comment]
Thanks for the suggestion - I added a short paragraph about it. Feel free to suggest more resources for setting it up in Debian if you have any.

That being said, as far as I am aware, timeshift's capabilities for `/home` do not all work correctly with KDE due to the latter requiring booting into a writable `/home/<user>`.

**Comment by danboid** [comment]
Thanks for your quick reply David!

I'd not heard of yabsnap before reading the updated guide. I shall have to check that out.

I don't think setting up timeshift under Debian needs its own guide. The only thing anyone needs to know about that is what I mentioned about the Debian Live installer creating the required subvols whereas the normal Debian installer doesn't. Setting up grub-btrfs is the same procedure as when using snapper as described in your guide.

**Comment by david-cortes** [comment]
@danboid By "Debian Live Installer", do you mean this one? https://www.debian.org/CD/live/

If so, is the difference there that the Calamares installer does the subvolume setup? What sort of option do you have to choose there in order to have BTRFS subvolumes for e.g. `/var/log` created by the installer?

**Comment by danboid** [comment]
Yes, that is the correct link to the Debian Live installation images that I'm referring to as being good for Timeshift.

You don't need to choose any special options during installation, the only requirement is that you choose the custom partition option and assign your / partition to be formatted with BTRFS because I'm pretty sure Debian Live still defaults to using ext4 otherwise, if you just choose the default partitioning option.
