### ISSUE TITLE
snapper-rollback vs snapper rollback

### ISSUE THREAD

**Issue by adminka-root** [david-cortes/snapper-in-debian-guide#6]
Could you please outline the differences between your package and the subcommand provided by snapper (snapper rollback)?

**Comment by david-cortes** [comment]
This is just a .md file, `snapper-rollback` comes from a different repository:
https://github.com/jrabinow/snapper-rollback

There's a GH issue there that I guess should answer your question: https://github.com/jrabinow/snapper-rollback/issues/16
